### ISSUE TITLE
Channel value prefix and suffix

### ISSUE THREAD

**Issue by julien-von-oetinger** [etn-ccis/blui-angular-component-library#547]
#### Describe the desired behavior

At the moment it is not possible to have something like `$5.00/minute` since you can have only one `units`.

#### Describe the current behavior

You can only have `$5.00` and then you must append and style `/minute` separately and manually.

#### Additional Context

Here is an example of what I currently do on my own:

![channel-value](https://user-images.githubusercontent.com/55489938/201325873-9def1a90-80a2-4e0c-825f-063ab648f8cd.png)

It is not a big deal but it would be nice to have an option to do this with the channel value component.

**Comment by jeffvg** [comment]
We recognize this is an inconvenience but at the moment we do not plan to include this in our design system.
