### ISSUE TITLE
Vertical scrollbar of the navigation menu is not displayed 

### ISSUE THREAD

**Issue by HafidZiti** [etn-ccis/blui-angular-component-library#560]
#### Describe the bugs
Vertical scrollbar isn't displayed when the navigation bar is collapsed
#### What is the expected behavior?
Display the verticals scrollbar when it is needed
#### What are the steps to reproduce?
1. Make sure you have at least 6 items in the navigation bar
1. Reduce the window screen(e.g:700x300)
2. Collapse the navigation bar 

#### Screenshots
![image](https://user-images.githubusercontent.com/24605755/208116890-c876791e-fbcc-436c-9087-4b3394824b61.png)

#### Suggested fix
As you can see on the flowing screenshot, a possible fix is to only hide `overflow-x` instead of hidden the whole `overflow`
![image](https://user-images.githubusercontent.com/24605755/208119259-0d994414-551b-45f5-8b15-52d933fafaf5.png)

**Comment by daileytj** [comment]
@HafidZiti, the suggestion looks good if you would you like to make a PR for this issue.
